<?php

const BOT_CONVERSATION_STATE = 'bot_conv_chat_';

const STORE_USERNAME_LETTER_LENGTH = 3;
const STORE_USERNAME_NUMBER_LENGTH = 3;
const STORE_EXPIRE_DATE = 60;
const TEXT_LENGTH_DEFAULT = 100;
const TEXT_LENGTH_ADDRESS_DEFAULT = 200;

const STORE_DET_KEY_NAME = 'name';
const STORE_DET_KEY_DESCRIPTION = 'description';
const STORE_DET_KEY_CONTACT1 = 'contact1';
const STORE_DET_KEY_ADDRESS = 'address';
